name: NonDex Flakiness Check

on:
  workflow_dispatch:  # allows manual trigger
  push:

jobs:
  test-flakiness:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Maven dependencies
      run: mvn -q -DskipTests clean install

    - name: Run normal test (expected pass)
      run: mvn -q test -Dtest=snippets.SnippetsTests#group_elements_by_length

    - name: Run NonDex (expected flaky)
      run: mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex \
              -DnondexRuns=10 \
              -Dtest=snippets.SnippetsTests#group_elements_by_length
